# TP7 : Fichier Makefile
#
include ../Makefile.inc

EXE = exercice1 exercice2 exercice3 exercice4 exercice_sem4 client serveur

all: ${EXE}

${EXE): ${PSE_LIB}

clean:
	rm -f *.o *~ ${EXE} journal.log


